base: '%env(TYPO3_BASEURL_MAIN)%'
errorHandling: []
languages:
  -
    title: Deutsch
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de_DE
    direction: ltr
    flag: de
    languageId: 0
routes: {  }
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: '/'
    index: ''
    map:
      sitemap.xml: 1533906435
rootPageId: 1
websiteTitle: ''
