include:
  - local: '/.build/ci/templates/deployTemplate.yml'
  - local: '/.build/ci/container-build.yml'
  - local: '/.build/ci/split-packages.yml'
  - local: '/.build/ci/linting-backend.yml'
  #- local: '/.build/ci/linting-frontend.yml'
  - local: '/.build/ci/documentation.yml'

#workflow:
#  rules:
#    - if: '$CI_COMMIT_BRANCH && $CI_PIPELINE_SOURCE == "push" && $CI_OPEN_MERGE_REQUESTS'
#      when: never # Do not run branch (push) pipelines when an MR is open on the branch
#    - when: always # Run all other pipeline types, or replace with specific workflow rule

stages:
  - devops-build
  - backend-linting
  - split-packages
  - documentation

cache:
  # each branch always use the same cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/.npm/
    - app/frontend/node_modules/
    - app/backend/vendor/

variables:
  APP_PUBLIC_DIRECTORY: 'public'
  DEPLOYMENT_PHP_BINARY: "$PHP_BINARY"
  # Tell composer to save and load it's cache within the .cache folder
  NODE_CACHE_DIR: "$CI_PROJECT_DIR/.cache/node_modules"
  COMPOSER_CACHE_DIR: "$CI_PROJECT_DIR/.cache/composer"
  SURF_WORKSPACE: "$CI_PROJECT_DIR/.caches/surf_workspace"
