include:
  - local: '/.build/ci/templates/deployTemplate.yml'
  - local: '/.build/ci/templates/containerTemplate.yml'
  #- local: '/.build/ci/linting-backend.yml'
  #- local: '/.build/ci/linting-frontend.yml'

#workflow:
#  rules:
#    - if: '$CI_COMMIT_BRANCH && $CI_PIPELINE_SOURCE == "push" && $CI_OPEN_MERGE_REQUESTS'
#      when: never # Do not run branch (push) pipelines when an MR is open on the branch
#    - when: always # Run all other pipeline types, or replace with specific workflow rule

stages:
  - split-packages

cache:
  # each branch always use the same cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/.npm/
    - app/frontend/node_modules/
    - app/backend/vendor/

variables:
  APP_PUBLIC_DIRECTORY: 'public'
  DEPLOYMENT_PHP_BINARY: "$PHP_BINARY"
  # Tell composer to save and load it's cache within the .cache folder
  NODE_CACHE_DIR: "$CI_PROJECT_DIR/.cache/node_modules"
  COMPOSER_CACHE_DIR: "$CI_PROJECT_DIR/.cache/composer"
  SURF_WORKSPACE: "$CI_PROJECT_DIR/.caches/surf_workspace"

split:packages:
  image:
    name: symplify2/monorepo-split:latest
    entrypoint: [ "/usr/bin/env" ]
  stage: split-packages
  parallel:
    matrix:
      -
        LOCAL_PATH: "app/backend/packages/starter"
        SPLIT_REPOSITORY: "starterteam/team/starter"
      -
        LOCAL_PATH: "app/backend/packages/starter_nessa"
        SPLIT_REPOSITORY: "starterteam/team/starter-nessa"
      -
        LOCAL_PATH: "app/backend/packages/starter_sitepackage"
        SPLIT_REPOSITORY: "starterteam/team/starter-sitepackage"
      -
        LOCAL_PATH: "app/backend/packages/starter_twig"
        SPLIT_REPOSITORY: "starterteam/team/starter-twig"
  variables:
    GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
    PACKAGE_DIRECTORY: $LOCAL_PATH
    REPOSITORY_ORGANIZATION: "team"
    REPOSITORY_NAME: $SPLIT_REPOSITORY
    BRANCH: "main"
    TAG: ""
    USER_NAME: $GITLAB_USER_NAME
    USER_EMAIL: $GITLAB_USER_EMAIL
    REPOSITORY_HOST: "gitlab.com"
  script:
    - echo "Splitting $PACKAGE_DIRECTORY to $REPOSITORY_NAME"
    - php /splitter/entrypoint.php
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      allow_failure: false
  interruptible: false
