include:
  - local: '/.gitlab/ci/container-build.yml'
  - local: '/.gitlab/ci/linting-backend.yml'
  - local: '/.gitlab/ci/linting-frontend.yml'
  - local: '/.gitlab/ci/split-packages.yml'
  - local: '/.gitlab/ci/documentation.yml'

#workflow:
#  rules:
#    - if: '$CI_COMMIT_BRANCH && $CI_PIPELINE_SOURCE == "push" && $CI_OPEN_MERGE_REQUESTS'
#      when: never # Do not run branch (push) pipelines when an MR is open on the branch
#    - when: always # Run all other pipeline types, or replace with specific workflow rule

stages:
  - devops-build
  - code-linting
  - split-packages
  - documentation

cache:
  # each branch always use the same cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/.npm/

variables:
  # Tell composer to save and load its cache within the .cache folder
  NODE_CACHE_DIR: "$CI_PROJECT_DIR/.cache/node_modules"
  COMPOSER_CACHE_DIR: "$CI_PROJECT_DIR/.cache/composer"
  BACKEND_DIR: "app/backend"
  FRONTEND_DIR: "app/frontend"
