.backend-linting:
  image: $CI_REGISTRY_IMAGE:backend
  variables:
    SCAN_FOLDER: "./app/backend/packages"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

stages:
  - backend-linting

###
# PHP syntax check
# see https://github.com/php-parallel-lint/PHP-Parallel-Lint
###
phplint:
  extends: .backend-linting
  stage: backend-linting
  variables:
    REPORT_FOLDER: "documentation/doc/code-quality"
    SCAN_FOLDER: "./app/backend/packages"
  script:
    - parallel-lint --colors -e php --blame --no-progress $SCAN_FOLDER > $REPORT_FOLDER/php-code-style.md

###
# PHP code style check
###
phpCS:
  stage: backend-linting
  variables:
    SCANNER_RELEASE: "https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar"
  script:
    - curl -OL $SCANNER_RELEASE
    - php ./phpcs.phar ./Classes --standard=PSR2 --colors
  tags:
    - docker

###
# TypoScript linter
###
typoscriptlint:
  stage: backend-linting
  script:
    - ./.craft/bin/typoscript-lint -c ./.build/typoscript-lint.yml --fail-on-warnings
  allow_failure: true
