.frontend-linting:
  stage: frontend-linting
  image: $CI_REGISTRY_IMAGE:frontend
  variables:
    SCAN_FOLDER: "./app/frontend/src"
    FRONTEND_FOLDER: "./app/frontend"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

stages:
  - frontend-linting

JavaScript:
  extends: .frontend-linting
  script:
    - cd ${CUSTOMER_SITEPACKAGE_PATH}/Build/ && npm install
    - ${FRONTEND_FOLDER}/node_modules/.bin/eslint --c ${CUSTOMER_SITEPACKAGE_PATH}/Build/.eslintrc.js --ignore-path ${CUSTOMER_SITEPACKAGE_PATH}/Build/.eslintignore "${CUSTOMER_SITEPACKAGE_PATH}/Build/Assets/JavaScript/**/*.js"
  only:
    changes:
      - ${CUSTOMER_SITEPACKAGE_PATH}/Build/JavaScript/*

Sass:
  extends: .frontend-linting
  script:
    - cd ${CUSTOMER_SITEPACKAGE_PATH}/Build/ && npm install
    - ${FRONTEND_FOLDER}/node_modules/.bin/stylelint "${SCAN_FOLDER}/**/*.scss" --config ${FRONTEND_FOLDER}/.stylelintrc --ignore-path ${FRONTEND_FOLDER}/.stylelintignore
  only:
    - merge_requests
