.frontend-linting:
  image: $CI_REGISTRY_IMAGE:frontend-$NODE_VERSION
  stage: code-linting
  cache:
    - key: ${CI_COMMIT_REF_SLUG}
      paths:
        - ${FRONTEND_DIR}/${STARTER_KIT}/node_modules/
  parallel:
    matrix:
      - NODE_VERSION: ['16.20.1']
        STARTER_KIT: [ 'starter_freya_fractal_starterkit', 'starter_nessa_starterkit' ]
  before_script:
    - cd ${FRONTEND_DIR}/${STARTER_KIT}/src/ && npm install

stages:
  - code-linting

frontend:JavaScript:
  extends: .frontend-linting
  script:
    - npm run lint:js
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - ${FRONTEND_DIR}/${STARTER_KIT}/src/**/*.js
        - ${FRONTEND_DIR}/${STARTER_KIT}/package.json
        - ${FRONTEND_DIR}/${STARTER_KIT}/package-lock.json


frontend:Sass:
  extends: .frontend-linting
  script:
    - npm run lint:scss
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - ${FRONTEND_DIR}/${STARTER_KIT}/src/**/*.scss
        - ${FRONTEND_DIR}/${STARTER_KIT}/package.json
        - ${FRONTEND_DIR}/${STARTER_KIT}/package-lock.json
