include:
  - local: '/.build/ci/templates/monorepoSplitTemplate.yml'

stages:
  - split-packages

split:packages:
  extends: .split-monorepo:template
  variables:
    TAG: ""
  script:
    - echo "Splitting $PACKAGE_DIRECTORY to $REPOSITORY_NAME"
    - php /splitter/entrypoint.php
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      allow_failure: false

split:packages:tagged:
  extends: .split-monorepo:template
  variables:
    TAG: $CI_COMMIT_TAG
  script:
    - echo "Splitting with tag ($TAG) $PACKAGE_DIRECTORY to $REPOSITORY_NAME"
    - php /splitter/entrypoint.php
  rules:
    - if: $CI_COMMIT_TAG
      allow_failure: false
